# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUuZ5z0mHlyndlQNZqVTECr0nYf5i9Pe
"""

def calculate_change(n, x):

    change = n - x
    if change < 0:
        print("支払い金額が不足しています。")
        return

    print(f"お釣りの総額: {change}円")


    coins = [500, 100, 50, 10]
    coin_count = {}


    for coin in coins:
        count = change // coin
        if count > 0:
            coin_count[coin] = count
            change -= coin * count


    for coin, count in coin_count.items():
        print(f"{coin}円: {count}枚")

    if change > 0:
        print(f"お釣りとして渡せない金額: {change}円")


if __name__ == "__main__":
    try:
        n = int(input("支払い金額を入力してください: "))
        x = int(input("商品の金額を入力してください: "))
        calculate_change(n, x)
    except ValueError:
        print("正しい数値を入力してください。")